First draft of spec
bgins/clock-transport-poc pull request #1
Opened 2020-12-05 22:00 UTC by bgins

A first draft outlining some of the requirements for this proof-of-concept.

2020-12-07 17:53 UTC, codyshepherd requested changes
Just a few suggested changes and requests for clarification of some terms. but otherwise looks good

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- Shared Data - the shared data structure
Maybe we should call this "master" or "server" data, or have some concept of that. As it is, I don't quite understand the definition of "shared data" if there is also "local data." There's a data structure on each client, and one or more on the server, and maybe several in flight, at any given time, right? Maybe I'm being pedantic but since each entity only has a view of its own instance of the data structure, calling it shared seems to muddle the issue a bit.

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- Clients modify independent parts of the schema. The data structure is shared, but to simplify synchronization, each user can only modify one part of the schema.
What does it mean for the data structure to be shared?

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- Each user has their own Clock. Clocks do not need to stay in sync with each other.
Are we making a distinction between "user" and "client?"

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- The Client sends Local Data updates to the Server immediately after sync but before Loop Start
I'm a bit confused on the order of operations described by this sentence. Can we define "sync"?

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +## Transport
Can we define "Transport?" The term is generic enough that context is not enough.

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- They play across Local Data
```suggestion
- the client audio display refers to local data```

2020-12-07 17:53 UTC, codyshepherd commented on spec.md
> +- They send updates to the Server
```suggestion
- The client sends updates to the serve when user makes a change```

2020-12-12 17:25 UTC, bgins commented on spec.md
> +- Shared Data - the shared data structure
Yes, good call. I was conflating "server" data and data that the client has received, but has not yet synced into their local data. Rewriting to separate those out.

2020-12-12 17:28 UTC, bgins commented on spec.md
> +- Clients modify independent parts of the schema. The data structure is shared, but to simplify synchronization, each user can only modify one part of the schema.
Was having trouble writing this clearly. The idea is that clients "own" one part of the data and can only modify that part. Will push an update like:

```
Clients own a section of the schema. A Client may only modify data that corresponds to a 
section they own. The goal is to simplify synchronization and prevent data tug-of-wars.
```

2020-12-12 17:29 UTC, bgins commented on spec.md
> +- Each user has their own Clock. Clocks do not need to stay in sync with each other.
Don't think we need to! Will update.

2020-12-12 17:45 UTC, bgins commented on spec.md
> +- The Client sends Local Data updates to the Server immediately after sync but before Loop Start
Rewriting this to clarify "sync". Short version, the client caches Server Data until the end of the loop. It update Local Data and that point and sends the updated version to the Server.

2020-12-12 17:46 UTC, bgins commented on spec.md
> +## Transport
Yep, will add a definition.

2020-12-12 17:58 UTC, bgins commented on spec.md
> +- They play across Local Data
Rewording this a bit, but will update.

2020-12-12 18:15 UTC, bgins commented
Thanks for the suggestions! I pushed some updates to address the comments. May still need more work to get all the details well-defined and clear.

2020-12-12 19:09 UTC, codyshepherd approved these changes
Thanks for the draft! This looks great. We can iterate on it as required while we develop.

2020-12-12 19:09 UTC, merged